## 人脸辨识

In [1]:
import face_recognition

In [2]:
#加载两张已知面孔的图片
known_obama_image=face_recognition.load_image_file(r"C:\Users\lmy\Desktop\人脸数据集\奥巴马\train1.jpg")
# known_obama_image=face_recognition.load_image_file(r"C:\Users\lmy\Desktop\OIP-C.jpg")
known_biden_image=face_recognition.load_image_file(r"C:\Users\lmy\Desktop\人脸数据集\川普\train.jpg")

In [3]:
known_obama_image.shape

(1322, 2000, 3)

In [10]:
face_recognition.face_encodings(known_obama_image)[0]

array([-1.18973553e-01,  1.17385998e-01,  6.98301867e-02, -3.73908244e-02,
        2.10069008e-02,  3.38665918e-02, -9.47531462e-02, -7.78539479e-02,
        1.61354765e-01, -1.30334973e-01,  2.78965503e-01,  8.07581693e-02,
       -2.13798076e-01, -1.33836165e-01,  7.42835701e-02,  1.37189716e-01,
       -1.86161220e-01, -8.81380290e-02, -9.98462662e-02, -8.67561921e-02,
        3.06037143e-02,  2.23313514e-02,  5.79081737e-02,  2.55351700e-02,
       -1.16594374e-01, -3.87129217e-01, -5.41898012e-02, -1.64131746e-01,
        1.06376028e-02, -1.35208949e-01, -1.09163135e-01, -2.83370037e-02,
       -1.68595850e-01, -4.60464656e-02, -2.43901014e-02, -2.05899850e-02,
        2.17053927e-02,  1.15536479e-02,  1.50875568e-01,  4.62008715e-02,
       -1.16074227e-01,  9.12253857e-02, -2.13156026e-02,  2.37002835e-01,
        2.61069626e-01,  8.47849995e-02,  2.56852694e-02, -8.84942636e-02,
        7.19043016e-02, -2.11346313e-01,  3.50845344e-02,  1.48845598e-01,
        6.72447830e-02,  

In [4]:
#计算图片对应的编码
img1_face_encoding=face_recognition.face_encodings(known_obama_image)[0]
img2_face_encoding=face_recognition.face_encodings(known_biden_image)[0]

In [14]:
known_encodings=[]

In [5]:
known_encodings=[
    img1_face_encoding,
    img2_face_encoding
]

In [13]:
known_encodings.append(img1_face_encoding)
known_encodings.append(img2_face_encoding)

In [8]:
img2_face_encoding.shape

(128,)

In [9]:
known_encodings

[array([-1.18973553e-01,  1.17385998e-01,  6.98301867e-02, -3.73908244e-02,
         2.10069008e-02,  3.38665918e-02, -9.47531462e-02, -7.78539479e-02,
         1.61354765e-01, -1.30334973e-01,  2.78965503e-01,  8.07581693e-02,
        -2.13798076e-01, -1.33836165e-01,  7.42835701e-02,  1.37189716e-01,
        -1.86161220e-01, -8.81380290e-02, -9.98462662e-02, -8.67561921e-02,
         3.06037143e-02,  2.23313514e-02,  5.79081737e-02,  2.55351700e-02,
        -1.16594374e-01, -3.87129217e-01, -5.41898012e-02, -1.64131746e-01,
         1.06376028e-02, -1.35208949e-01, -1.09163135e-01, -2.83370037e-02,
        -1.68595850e-01, -4.60464656e-02, -2.43901014e-02, -2.05899850e-02,
         2.17053927e-02,  1.15536479e-02,  1.50875568e-01,  4.62008715e-02,
        -1.16074227e-01,  9.12253857e-02, -2.13156026e-02,  2.37002835e-01,
         2.61069626e-01,  8.47849995e-02,  2.56852694e-02, -8.84942636e-02,
         7.19043016e-02, -2.11346313e-01,  3.50845344e-02,  1.48845598e-01,
         6.7

In [5]:
#加载1张未知面孔的测试图片（test）
image_to_test = face_recognition.load_image_file(r"C:\Users\lmy\Desktop\test.jpg")

In [6]:
#计算图片对应的编码
image_to_test_encoding= face_recognition.face_encodings(image_to_test)[0]

In [7]:
#计算未知图片与已知的两个面孔的距离
face_distances =face_recognition.face_distance(known_encodings,image_to_test_encoding)

In [8]:
for i in face_distances:
    print(i)

0.38161688946583444
0.8793238220188805


In [23]:
face_distances

array([0.38161689, 0.87932382])

In [55]:
len(known_encodings)

2

In [23]:
face_distances[my_array[0]]

0.38161688946583444

In [19]:
# 创建一个字典
my_array = {}
#     "label1": "element1",
#     "label2": "element2",
#     "label3": "element3"
# 获取标签对应的元素
# element = my_array["label1"]
# print(element)  # 输出：element1




In [20]:
jishuface_class=0

In [28]:
jishuface_class+=1

In [29]:
jishuface_class

3

In [21]:
my_array[jishuface_class]=0

In [22]:
# 遍历字典的键值对
for label, element in my_array.items():
    print(label, element)

0 0


## softmax 公式

In [58]:
import numpy
def softmax(inMatrix):
    m,n=numpy.shape(inMatrix)
    outMatrix= numpy.mat(numpy.zeros(m,n))
    soft_sum=0
    for idx in range(0,n):
        outMatrix[0,idx]=math.exp(inMatrix[0,idx])
        sift_sum+= outMatrix[0,idx]
    for idx in range(0,n):
        outMatrix[0,idx]=outMatrix[0,idx]/soft_sum
    return outMatrix

In [57]:
a=numpy.array([[1,2,1,1,2,1,2,3,4]])

In [16]:
import tensorflow as tf

In [2]:
tf.constant(1.)+tf.constant(1.)

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [3]:
text = tf.constant("Hello Tensorflow 2.1")
print(text)

tf.Tensor(b'Hello Tensorflow 2.1', shape=(), dtype=string)


In [8]:
from sklearn.datasets import load_iris

In [9]:
import numpy as np

In [10]:
data = load_iris()

In [11]:
iris_target =data.target

In [13]:
iris_data=np.float32(data.data)

In [20]:
iris_target = np.float32(tf.keras.utils.to_categorical(iris_target,num_classes=3))

In [22]:
iris_data=tf.data.Dataset.from_tensor_slices(iris_data).batch(50)

In [25]:
iris_target=tf.data.Dataset.from_tensor_slices(iris_target).batch(50)

In [26]:
iris_target

<BatchDataset shapes: (None, 3), types: tf.float32>

## 人脸检测

In [38]:
import cv2
import dlib
import numpy as np

In [28]:
image = cv2.imread(r"C:\Users\lmy\Desktop\train.jpg")

In [36]:
detector = dlib.get_frontal_face_detector()#Dlib创建的检测器
boundarys= detector(image,2)#对人脸图片进行检测，找到人脸的位置框
print(list(boundarys))#打印位置框内容

[rectangle(582,361,915,694)]


#### 框体上方 ：rectangle[1]  使用函数rectangle.top()获取
#### 框体下方 ：rectangle[3]  使用函数rectangle.bottom()获取
#### 框体左方 ：rectangle[0]  使用函数rectangle.left()获取
#### 框体右方 ：rectangle[2]  使用函数rectangle.right()获取

In [37]:
draw = image.copy()
rectangles=list(boundarys)
for rectangle in rectangles:
    top = np.int(rectangle.top())
    bottom=np.int(rectangle.bottom())
    left = np.int(rectangle.left())
    right=np.int(rectangle.right())

print([left,top,right,bottom])

[582, 361, 915, 694]


C:\Users\lmy\AppData\Local\Temp\ipykernel_11408\688444738.py:4: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  top = np.int(rectangle.top())
C:\Users\lmy\AppData\Local\Temp\ipykernel_11408\688444738.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for ad

## 人脸截取

In [25]:
import cv2
import dlib
import numpy as np
image = cv2.imread(r"C:\Users\lmy\Desktop\人脸数据集\合影\1.jpg")
detector = dlib.get_frontal_face_detector()#Dlib创建的检测器
boundarys= detector(image,2)#对人脸图片进行检测，找到人脸的位置框
draw = image.copy()
rectangles=list(boundarys)
for rectangle in rectangles:
    top = np.int(rectangle.top())
    bottom=np.int(rectangle.bottom())
    left = np.int(rectangle.left())
    right=np.int(rectangle.right())
    
    W = -int(left)+int(right) #获取人脸框体的宽度
    H = -int(top)+int(bottom) #获取人脸框体的高度
    paddingH=0.01*W
    paddingW=0.02*H
    #将人脸的图片单独“切割出来”
    crop_img=image[int(top+paddingH):int(bottom-paddingH),int(left-paddingW):int(right+paddingW)]
    #进行人脸框体描绘
    cv2.rectangle(draw,(int(left),int(top)),(int(right),int(bottom)),(255,0,0),1)
    cv2.imshow("test",draw)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
print([left,top,right,bottom])

TypeError: __call__(): incompatible function arguments. The following argument types are supported:
    1. (self: _dlib_pybind11.fhog_object_detector, image: numpy.ndarray, upsample_num_times: int = 0) -> _dlib_pybind11.rectangles

Invoked with: <_dlib_pybind11.fhog_object_detector object at 0x0000024A1F7F5FB0>, None, 2

In [ ]:
file_dirs